version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      #- aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      #- eval $(aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 3062-7481-2096.dkr.ecr.us-west-1.amazonaws.com)
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p2w0c5l8
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - eval $(docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .)
      #- docker tag public.ecr.aws/p2w0c5l8/ecr-public:latest  3062-7481-2096.dkr.ecr.us-west-1.amazonaws.com/public.ecr.aws/p2w0c5l8/ecr-public:latest  
      - eval $(docker tag ecr-public public.ecr.aws/p2w0c5l8/ecr-public:latest)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - eval $(docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG)
